# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='enthusiasm',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='priority',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
