# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 03:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arrangements', '0003_auto_20170629_0033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='author',
            new_name='user',
        ),
    ]
