# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangements', '0007_auto_20170630_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_chosen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='is_search',
            field=models.BooleanField(default=False),
        ),
    ]
