# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangements', '0008_auto_20170630_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_arranged',
            field=models.BooleanField(default=False),
        ),
    ]
