# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 16:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('arrangements', '0009_activity_is_arranged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 3, 16, 39, 43, 109568, tzinfo=utc)),
        ),
    ]
